apiVersion: apps/v1
kind: Deployment
metadata:
  name: extracto-spider-worker
  namespace: extracto
  labels:
    app: extracto-spider-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: extracto-spider-worker
  template:
    metadata:
      labels:
        app: extracto-spider-worker
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: worker
        image: ghcr.io/kkogaa/extracto-spider-worker:64eeaad
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: "redis.extracto.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
